### ISSUE TITLE
Parse Charged/Rechargeable Actions

### ISSUE THREAD

**Issue by Krigsmaskine** [EthanJWright/foundryvtt-importer#47]
Thanks a ton for your module, I think you're single handedly holding back my evolving carpal tunnel syndrome right now. :9 

**Is your feature request related to a problem? Please describe.**
When parsing actors by using monster blocks, it seems that content parser always has an issue with attacks that has a recharge, like Breathe Fire (Recharge 5-6). It instead amends the attack with a recharge to the feature that preceded it, so if you had a Claw attack and a Breathe Fire attack, the entire description of Breathe Fire would be in the Claw skill description.

**Describe the solution you'd like**
Preferably at least a feature created from the recharged attack, if it could actually be coded to recharge, that'd be double sweet, but mostly icing on the cake. Just saving the extra clicks of creating a new feature would be amazing.

Examples can be pulled from the SRD, since I can't really share other source material, but essentially all the dragons have a recharge ability to look at for examples.

**Comment by EthanJWright** [comment]
Thanks for this, I add parsing features as they come up for me, or as people open issues, and so I'm sure recharge is not super well tested - I'll add some tests and get this patched, thanks for the issue!

**Comment by EthanJWright** [comment]
Fixed in #49 

I *believe* I addressed all of your comments. The issue where it was adding the feature with recharge to the preceding feature should certainly be fixed. I'm also now parsing the recharge value and adding it to the 5E model which should get you what you're looking for? If I missed anything feel free to open another bug or a feature request, but I'm pretty sure this addressed all of your issues.

Thanks for opening this and helping me catch bugs and edge cases!
